### ISSUE TITLE
Update doc with new behaviour without paramers.sh

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#111]
here: https://spine-generic.readthedocs.io/en/latest/documentation.html#generate-figures

the doc instructs to use a parameters.sh file, but we don't have that anymore. So, doc should be updated

**Comment by valosekj** [comment]
This issue has been closed, however doc has not been updated. There is more to update in doc. I will open separate issue with task-list.

**Comment by jcohenadad** [comment]
you're right-- the issue shouldn't have been closed-- we can continue here

**Comment by jcohenadad** [comment]
well, now that https://github.com/spine-generic/spine-generic/issues/112 has been opened, we can close this one
