### ISSUE TITLE
Acquisition parameters QC

### ISSUE THREAD

**Issue by alexfoias** [spine-generic/spine-generic#113]
In the original version of the manuscript we had this paragraph and suggestion.

```
To make sure the protocol was followed without modifying the sequence parameters, the protocol used by each site was exported in pdf and sent to the central site for QCAing.

that's old school-- we should make a BIDS-friendly script to verify the parameters. 
```

@jcohenadad I started to work on a script using pybids. I would like to know on what parameters should we focus for an initial iteration. I thought of checking TR,TE,FA.

The strategy is to query the dataset and grab each contrast's metadata. This metadata will be compared to the template stored in a json file with specific sections for scanner, software version, contrast, TR,TE,FA. If they don't match a warning message will be triggered.

**Comment by jcohenadad** [comment]
awesome! 
could you instead please implement those as CI in the respective BIDS datasets repos: https://github.com/spine-generic/data-single-subject/issues/1

and yes, start with the typical params (TR, YE, etc) and we'll take it from there
