### ISSUE TITLE
Move manual corrections under derivatives/labels/

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#117]
They are currently under derivatives/, and according to [BIDS recommendations](https://github.com/bids-standard/bids-starter-kit/wiki/The-BIDS-folder-hierarchy) it should go under a deeper folder, e.g. `derivatives/labels`.

TODO:
- [x] Update https://github.com/spine-generic/data-single-subject
- [x] Update process_data.sh in this repos
- [ ] ~Add a README under derivatives/~ not needed

**Comment by valosekj** [comment]
Also `manual_correction.py` script (https://github.com/spine-generic/spine-generic/pull/103) should be fixed. Fortunately it should be easy by modifying following line:

https://github.com/spine-generic/spine-generic/blob/f4fb69a78fe40b81292d1422f0758c4d60249e58/processing/manual_correction.py#L42

to 

`self.folder_derivatives = 'derivatives/labels' `

**Comment by valosekj** [comment]
And also[ populate_derivatives.py](https://github.com/spine-generic/spine-generic/blob/master/processing/populate_derivatives.py) script needs to be fixed. Probably again only one this one line:

https://github.com/spine-generic/spine-generic/blob/a1c05569f0f281f02ab0324fdf5e6f3aa28791e5/processing/populate_derivatives.py#L29

**Comment by jcohenadad** [comment]
> Also `manual_correction.py` script (#103) should be fixed. Fortunately it should be easy by modifying following line:
> 
> https://github.com/spine-generic/spine-generic/blob/f4fb69a78fe40b81292d1422f0758c4d60249e58/processing/manual_correction.py#L42
> 
> to
> 
> `self.folder_derivatives = 'derivatives/labels' `

fixed in #106
