### ISSUE TITLE
Allow exclusion of subject/site using yaml for generate_figure.py

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#125]
Currently, subjects and sites to exclude from generating figures are defined directly inside [generate_figure.py](https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/generate_figure.py) script. It would be better to pass this information as input yaml config file.

**Comment by alexfoias** [comment]
@valosekj are you working on this issue ? If not, I can implement a solution for it. Thanks.

**Comment by valosekj** [comment]
> @valosekj are you working on this issue ? 

No, I am not. 

> If not, I can implement a solution for it. Thanks.

It would be great 👍
