### ISSUE TITLE
Manual labeling should be done on each disc

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#137]
Currently, manual correction for labeling is to point at C3 and C5. While this works well for the scope of spine-generic analysis, this is a problem if the data are to be used by other projects, e.g., automatic labeling by @lrouhier. 

As an illustration, the manual ground-truth produced below is wrong below C7:

![Screen Shot 2020-07-14 at 11 49 10 AM](https://user-images.githubusercontent.com/2482071/87447159-3b76e480-c5c8-11ea-8c98-412effed7b31.png)

Alternatively, during manual correction, user should point at each disc location. Then, a labeled segmentation should be created from these labels.

**Comment by valosekj** [comment]
Decision if manually correct only C3 and C5 (how is currently implemented for spine-generic) or every disc could be passed to `sg_manual_correction.py` script as optional input argument. Or it could be set inside `-config` yaml file. Then, for spine-generic project, manual correction of C3 and C5 could stay and for another project could be passed correction of another (or all) discs.

**Comment by jcohenadad** [comment]
Closing because as mentioned ^ this wish is out of the score of the spine-generic project. Specific disc labels could be created as part of another project.
