### ISSUE TITLE
Create a json sidecar along with the manual corrections

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#143]
To track provenance, it would be important to create json files along with the corrected manual segmentations and labels.

The json file would include the following:
````xml
{
  "Author": "Firstname Lastname"
}
````

**Comment by jcohenadad** [comment]
A suggestion would be to include a tag "name" in the yml file that is input in `sg_correct_segmentation`. @valosekj what do you think?

**Comment by valosekj** [comment]
The resulting yml file would look something like that?:

```
FILES_SEG:
- sub-amu01_T1w_RPI_r.nii.gz
- sub-amu01_T2w_RPI_r.nii.gz
- sub-cardiff02_dwi_moco_dwi_mean.nii.gz
FILES_GMSEG:
- sub-amu01_T2star_rms.nii.gz
FILES_LABEL:
- sub-amu01_T1w_RPI_r.nii.gz
- sub-amu02_T1w_RPI_r.nii.gz
NAME:
- Firstname Lastname
```

What about including also date when corrections were performed? Do we need it?

**Comment by jcohenadad** [comment]
adding the date is a good idea. i'll add it
