### ISSUE TITLE
error while plotting sg_generate_figure

### ISSUE THREAD

**Issue by PaulBautin** [spine-generic/spine-generic#148]
When running sg_generate_figure following error is printed. Any idea?

**Error:**
Loop across subjects: 100%|███████████████| 253/253 [00:00<00:00, 1007.05iter/s]
Subjects removed: ['sub-oxfordFmrib04']
Created: fig_csa_t2.png

Processing: csa-SC_T1w.csv
Loop across subjects: 100%|███████████████| 253/253 [00:00<00:00, 1007.81iter/s]
Subjects removed: ['sub-oxfordFmrib04']
Created: fig_csa_t1.png
Traceback (most recent call last):
File "/home/paul/.local/bin/sg_generate_figure", line 33, in
sys.exit(load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')())
File "/home/paul/github/spine-generic/spinegeneric/cli/generate_figure.py", line 606, in main
plt.scatter(np.concatenate(CSA_dict[vendor + '_t2'], axis=0),
File "/home/paul/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2811, in scatter
__ret = gca().scatter(
File "/home/paul/.local/lib/python3.8/site-packages/matplotlib/init.py", line 1565, in inner
return func(ax, *map(sanitize_sequence, args), **kwargs)
File "/home/paul/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
return func(*args, **kwargs)
File "/home/paul/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4380, in scatter
raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size

**Comment by jcohenadad** [comment]
@PaulBautin can you please always indicate the git commit of the code you've used as well as the data provenance (which data release?), to help us reproduce the error-- thanks

**Comment by PaulBautin** [comment]
git commit: https://github.com/spine-generic/spine-generic/tree/4709dc373dc640b2da2f775e9e979ad37b5a10ea
data: https://github.com/spine-generic/data-multi-subject/releases/tag/r20200722

**Comment by jcohenadad** [comment]
> data: https://github.com/spine-generic/data-multi-subject/releases/tag/r20200722

i think you meant this: https://github.com/spine-generic/data-multi-subject/releases/download/r20200722/sct_run_batch_20200722022726.zip

(which are the results, including the csv files, with which you can run `sg_generate_figure`

**Comment by alexfoias** [comment]
I managed to reproduce almost the same behaviour.

Using version 225717b87be48a75b07015edb136333614ae4310 and [data](https://github.com/spine-generic/data-multi-subject/releases/download/r20200722/sct_run_batch_20200722022726.zip)

Here is my output:
```
(base) alfoi@MacBook-Pro:spine-generic % sg_generate_figure -path-results /Users/alfoi/Downloads/sct_run_batch_20200722022726/results 

Processing: DWI_RD.csv
Loop across subjects: 100%|████████████████| 250/250 [00:00<00:00, 745.33iter/s]
Subjects removed: []
Created: fig_dti_rd.png

Processing: DWI_FA.csv
Loop across subjects: 100%|████████████████| 250/250 [00:00<00:00, 765.07iter/s]
Subjects removed: ['sub-beijingPrisma03', 'sub-oxfordFmrib01']
Created: fig_dti_fa.png

Processing: csa-SC_T2w.csv
Loop across subjects: 100%|████████████████| 253/253 [00:00<00:00, 539.65iter/s]
Subjects removed: ['sub-oxfordFmrib04']
Created: fig_csa_t2.png

Processing: DWI_MD.csv
Loop across subjects: 100%|████████████████| 250/250 [00:00<00:00, 742.56iter/s]
Subjects removed: []
Created: fig_dti_md.png

Processing: MTR.csv
Loop across subjects: 100%|████████████████| 243/243 [00:00<00:00, 736.89iter/s]
Subjects removed: ['sub-beijingPrisma04', 'sub-geneva02']
Created: fig_mtr.png

Processing: MTsat.csv
Loop across subjects: 100%|████████████████| 243/243 [00:00<00:00, 736.93iter/s]
Subjects removed: ['sub-tehranS04', 'sub-geneva02']
Created: fig_mtsat.png

Processing: csa-GM_T2s.csv
Loop across subjects: 100%|████████████████| 252/252 [00:00<00:00, 551.69iter/s]
Subjects removed: []
Created: fig_csa_gm.png

Processing: csa-SC_T1w.csv
Loop across subjects: 100%|████████████████| 253/253 [00:00<00:00, 689.96iter/s]
Subjects removed: ['sub-oxfordFmrib04']
Created: fig_csa_t1.png

Processing: T1.csv
Loop across subjects: 100%|████████████████| 243/243 [00:00<00:00, 757.12iter/s]
Subjects removed: ['sub-sapienza04', 'sub-sapienza03', 'sub-sapienza05', 'sub-sapienza06']
Created: fig_t1.png
Traceback (most recent call last):
  File "/Users/alfoi/miniconda3/bin/sg_generate_figure", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')()
  File "/Users/alfoi/code/spine-generic/spinegeneric/cli/generate_figure.py", line 612, in main
    label=vendor)
  File "/Users/alfoi/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2816, in scatter
    None else {}), **kwargs)
  File "/Users/alfoi/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/alfoi/miniconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/Users/alfoi/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4391, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size
```

**Comment by jcohenadad** [comment]
@alexfoias can you pls look into it?

**Comment by alexfoias** [comment]
The error comes from the fact that for **GE** & **Philips** the _CSA_dict_ for **t1** & **t2** are not equal:
```
GE
len (CSA_dict_t2): 32
len (CSA_dict_t1): 30
Philips
len (CSA_dict_t2): 48
len (CSA_dict_t1): 49
```

The files: **csa-SC_T1w.csv** and **csa-SC_T2w.csv** have the same # of rows & columns.

@jcohenadad Do you have an idea where does it come from ? The subjects mentioned in **SUBJECTS_TO_REMOVE** (CSA section) are Siemens.

**Comment by valosekj** [comment]
Try this https://github.com/spine-generic/spine-generic/commit/fd1bef307efa17441eef3962285c55fcb4d4c4db. There was bug in code. It is necessary to sort values by site instead of vendors. And then add exclusion of `sub-mountSinai03` t1w to fit x and y lengths.

**Comment by alexfoias** [comment]
@valosekj thanks for the tip. The https://github.com/spine-generic/spine-generic/commit/fd1bef307efa17441eef3962285c55fcb4d4c4db seems to fix the problem. You should mention it in the PR.
