### ISSUE TITLE
flag -qc does not exist in sct_labels_utils

### ISSUE THREAD

**Issue by PaulBautin** [spine-generic/spine-generic#152]
`sg_manual_correction` fails when correcting vertebrae labelings. Error is displayed ==> 
```
Command-line usage error: argument -qc does not exist. Did you mean: -o, -i, -v?
Aborted...
```
Indeed flag -qc is not present in `sct_label_utils`. See listed flags in error output ==>

[err_flag_qc_manual_corr.txt](https://github.com/spine-generic/spine-generic/files/4997562/err_flag_qc_manual_corr.txt)

git commit: https://github.com/spine-generic/spine-generic/tree/398594483c7b0dac456ff15642ec5a03e929fcc9

**Comment by jcohenadad** [comment]
@PaulBautin update your SCT version to master

**Comment by PaulBautin** [comment]
It works. I will close this issue because error was local, coming from SCT version
