### ISSUE TITLE
Improve workflow for generating QC of manual corrections

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#159]
In this example: https://github.com/spine-generic/data-multi-subject/pull/16, there were several back-and-forth between the contributor and the user, so at the end there is no single QC report that matches all the committed files on the branch, making it difficult to do a full review at once, and make sure there was no manual error between the back-and-forth.

One possibility would be to have the option to generate a "final" QC report, within the `sg_manual_correction` function, by looking at the files that are different between the master branch and the working branch. @valosekj @PaulBautin @kousu do you have comments/ideas?

**Comment by jcohenadad** [comment]
Actually, a simple solution would be to have a function that _just_ generate a QC, based on the yml config file.

**Comment by jcohenadad** [comment]
Maybe we can add a flag `sg_manual_correction -only-qc` to only output the QC report. Any thoughts @valosekj @PaulBautin ?

**Comment by PaulBautin** [comment]
Unless it is not the only function with this complication (in which case function should have a broader scope), seems great! Would the only needed input be the derivative files?

**Comment by jcohenadad** [comment]
> Would the only needed input be the derivative files?

not sure i understand this comment.

the input would be the same as what you typed-- the only difference is that the flag -qc-only would skip the copy and manual correction (ie only does the qc report, based on the derivatives that are _already_ corrected)

**Comment by jcohenadad** [comment]
ok i'll work on a fix-- shouldn't be long

**Comment by valosekj** [comment]
> Maybe we can add a flag `sg_manual_correction -only-qc` to only output the QC report. 

Sounds as the good solution 👍

**Comment by valosekj** [comment]
> In this example: [spine-generic/data-multi-subject#16](https://github.com/spine-generic/data-multi-subject/pull/16), there were several back-and-forth between the contributor and the user

you mean that user did manual correction but admin requested some extra edit/improving only for some subjects? Something like I did [here](https://github.com/spine-generic/data-multi-subject/pull/15#issuecomment-666147461)? I achieved manual correction only for one subject by creating new yml file only with one filename of certain subject. I think if I run `sg_manual_correction` script with original yml file (containing all filenames) and would like to skip some subjects by simply closing FSLeyes, `sg_manual_correction` would despite it replace previous manually corrected segmentation by new copies by shutil.copy command.
So I had to pay attention about not overwriting previously created manual corrections.

**Comment by jcohenadad** [comment]
> So I had to pay attention about not overwriting previously created manual corrections.
(I realized it fully when trying #160)

indeed, that's a **major** flaw in the current implementation-- we should probably add a warning, that let the user know that the file "-manual" already exists, and if he is sure he wants to continue.
