### ISSUE TITLE
sg_generate_figure ylabel cosmetic issues

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#163]
I have found two cosmetic issues when plotting figures using `sg_generate_figure` script:

1. Last digit in labels on y-axis in mean and radial diffusivity (MD and RD) figures is not in superscript:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/39456460/89269812-b6b53e80-d63a-11ea-871a-184ecea7506e.png">

2. Magnetic transfer saturation has `a.u.` as an unit, but fractional anisotropy has no unit. Don't we want to unify this, i.e., add `a.u.` also for FA or delete `a.u.` from MTsat label?

<img width="227" alt="image" src="https://user-images.githubusercontent.com/39456460/89269831-be74e300-d63a-11ea-8cec-67dc851edcd8.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/39456460/89269857-c6348780-d63a-11ea-85ca-8e1fd02b1087.png">

I could fix this.

**Comment by jcohenadad** [comment]
thanks for looking into it @valosekj !

for 2.: i would get rid of the a.u.
