### ISSUE TITLE
Rename sapienza --> fslAchieva

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#165]
After merging https://github.com/spine-generic/data-multi-subject/pull/21, we should rename here (and at other places):

https://github.com/spine-generic/spine-generic/blob/1329c37e40569ab22c37526d2d3ac9eb2b8f23a6/spinegeneric/cli/generate_figure.py#L60

**Comment by alexfoias** [comment]
I can work on this.

**Comment by alexfoias** [comment]
@jcohenadad Can I also add fslPrisma in the flags sections ? or should I open another PR for that ?

**Comment by jcohenadad** [comment]
> @jcohenadad Can I also add fslPrisma in the flags sections ?

👍
