### ISSUE TITLE
Inconsistency in comment for RESTORE

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#169]
this line says we used RESTORE: https://github.com/spine-generic/spine-generic/blob/master/process_data.sh#L292

but at the end we did not

**Comment by valosekj** [comment]
Do we want to only clarify line with the comment (i.e., delete info about RESTORE) or switch algorithm from standard to restore?:

https://github.com/spine-generic/spine-generic/blob/e457dbc0afd184725a95f6ce9f386f45f5b069f4/process_data.sh#L293

**Comment by jcohenadad** [comment]
only clarify comment
