### ISSUE TITLE
generate_figure: ValueError: x and y must be the same size occurs if T1w and T2w subjects do not match

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#193]
If the subjects don't match between T1w and T2w, the following error is raised:
~~~
Traceback (most recent call last):
  File "/Users/julien/miniconda3/bin/sg_generate_figure", line 11, in <module>
    load_entry_point('spinegeneric', 'console_scripts', 'sg_generate_figure')()
  File "/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/generate_figure.py", line 791, in main
    generate_figure_t1_t2(df, csa_t1, csa_t2)
  File "/Users/julien/code/spine-generic/spine-generic/spinegeneric/cli/generate_figure.py", line 555, in generate_figure_t1_t2
    label=vendor)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2841, in scatter
    None else {}), **kwargs)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/julien/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4443, in scatter
    raise ValueError("x and y must be the same size")
ValueError: x and y must be the same size
~~~

An elegant solution would be to ignore the subject _both_ for T1w and T2w, in case it is excluded in one of them. 

~Another (quick) solution is to ignore the excluded subjects.~ 

**Update**: oopsi! i tried running the code without the `-exclude` flag and the same error happens 😞

**Comment by jcohenadad** [comment]
> Update: oopsi! i tried running the code without the -exclude flag and the same error happens 😞

actually, this was caused by corrupted csv files with duplicated subjects (process run several times):
[Archive.zip](https://github.com/spine-generic/spine-generic/files/5176109/Archive.zip)

so, ignoring excluded subjects _should_ work.

**Comment by valosekj** [comment]
I have just tried to generate this figure with previous release of results ([r20200830](https://github.com/spine-generic/data-multi-subject/releases/tag/r20200830)) and it fails on the same error. 
When I go deeper inside, both `csa-SC_T1w.csv` and `csa-SC_T2w.csv` have same number of lines, i.e., same number sites. But when I do not use any exclusion, for Siemens I have totally 173 values (i.e., 173 subjects) for t1 (`np.concatenate(CSA_dict[vendor + '_t1']`), but for t2 I have 172 values (i.e., 172 subjects) (`np.concatenate(CSA_dict[vendor + '_t2']`). This causes discrepancy for length of x and y axis.

https://github.com/spine-generic/spine-generic/blob/4143cbfd7a206f06e3fd9f42485d5087129899d7/spinegeneric/cli/generate_figure.py#L549-L550

How is possible that Siemens has for t1 different number of subjects than for t2 when I do not use any `exlude.yml`?

**Comment by jcohenadad** [comment]
> How is possible that Siemens has for t1 different number of subjects than for t2 when I do not use any exlude.yml?

which site is missing?

**Comment by valosekj** [comment]
Missing is `sub-mountSinai03`. The reason is because this site has in `csa-SC_T2w.csv` file value `None`:

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/39456460/92277269-3e70c000-eefb-11ea-81f5-bd828dc12ebe.png">

It is reason why this site is listed in `exclude.yml`:
https://github.com/spine-generic/data-multi-subject/blob/6bda590b10ec08315265f40ca0eda6b9e9c7eb04/exclude.yml#L13

Current implementation of generate_figure.py obviously discards `None` and without using `exclude.yml`, discrepancy in length of t1 and t2 (i.e., x and y axis) happens.

**Comment by valosekj** [comment]
> An elegant solution would be to ignore the subject _both_ for T1w and T2w, in case it is excluded in one of them.

This would be really elegant solution. I can implement it. Unfortunately, I will have time for it after weekend. Until that, exclude.yml file has to include subject under both `csa_t1` and `csa_t2` flags even if the problem is only in one contrast.
