### ISSUE TITLE
Add iframe to show good-quality data

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#202]
It would be nice to embed a nifti viewer in our RTD, to show examples of good quality data.

Technologies to embed niftis include:
- https://brainsprite.github.io/ --> looks like this is the winner! 🎉   (and made by Pierre Bellec)
- https://github.com/rii-mango/Papaya
- https://github.com/FNNDSC/ami
- https://brainbrowser.cbrain.mcgill.ca/

or via Python code:
- NiftiWidget: https://github.com/jcohenadad/GBM8378/blob/master/lab3-irm/gbm8378-lab3-irm.ipynb

**Comment by jcohenadad** [comment]
info from Pierre: to generate the html to embed, view_img  from nilearn can be used

**Comment by alexfoias** [comment]
@jcohenadad could you please point me to some good quality data so that I could use to implement the viewer ? thanks.

**Comment by alexfoias** [comment]
Here is a test, please open the file **click_here.html**
[test_unf1.zip](https://github.com/spine-generic/spine-generic/files/5196184/test_unf1.zip)

The only problem that I see is the contrast that is a bit strange. Not sure if we can change the contrast, unless we open an issue on https://brainsprite.github.io/

**Comment by jcohenadad** [comment]
> @jcohenadad could you please point me to some good quality data so that I could use to implement the viewer ? thanks.

in the spine-generic manuscript, see: Figure GOOD_DATA

**Comment by jcohenadad** [comment]
> The only problem that I see is the contrast that is a bit strange. Not sure if we can change the contrast, unless we open an issue on https://brainsprite.github.io/

ah, good point. Let me ask Pierre, maybe he has a quick answer.

**Comment by alexfoias** [comment]
my bad, I fixed the contrast. Here is a good example
[test_unf1.zip](https://github.com/spine-generic/spine-generic/files/5196221/test_unf1.zip)

**Comment by jcohenadad** [comment]
awesome! how did you fix it?

**Comment by alexfoias** [comment]
```
bsprite = viewer_substitute(cmap='gray', symmetric_cmap=False, black_bg=True,
                         threshold=None, vmax=1500, title="anatomical scan", value=False)
```

I changed the **vmax** from 200 to 1500

**Comment by alexfoias** [comment]
where should we insert this iframe ?

**Comment by jcohenadad** [comment]
> where should we insert this iframe ?

I'm thinking there --> https://spine-generic.readthedocs.io/en/latest/data-acquisition.html#multi-center-data

**Comment by alexfoias** [comment]
Here is an output example for contrast from Figure GOOD_DATA
[results_contrasts_good.zip](https://github.com/spine-generic/spine-generic/files/5197685/results_contrasts_good.zip)

I don't know how to get rid of the brain behind some images. I checked in the [documentation](https://brainsprite.github.io/APIPY.html), but I couldn't find the option

**Comment by jcohenadad** [comment]
> I don't know how to get rid of the brain behind some images. I checked in the [documentation](https://brainsprite.github.io/APIPY.html), but I couldn't find the option

probably [that](https://brainsprite.github.io/APIPY.html#brainsprite.viewer_substitute.fit) (under `bg_img`)

**Comment by alexfoias** [comment]
I change `bg_img=False` and it did the trick. Now we have another problem. The images are squished.

See here: 
[results_no_background.zip](https://github.com/spine-generic/spine-generic/files/5204309/results_no_background.zip)

**Comment by jcohenadad** [comment]
@alexfoias could you open an issue on brainsprite?

**Comment by alexfoias** [comment]
https://github.com/brainsprite/brainsprite/issues/98

I opened the issue here: https://github.com/brainsprite/brainsprite/issues/98

**Comment by alexfoias** [comment]
@jcohenadad where should I put the scripts for creating the htmls ?

**Comment by jcohenadad** [comment]
> @jcohenadad where should I put the scripts for creating the htmls ?

how long is that? maybe it would be more appropriate in the wiki actually...
