### ISSUE TITLE
Automatize text generation based on results

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#204]
When writing the results section of the spine-generic manuscript, there is a lot of manual copy/paste of the statistics, which is slow and prone to human error.

A better way would be to generate the text and auto-fill the results. Here would be the template:
~~~
The intra-site coefficients of variation (COVs) were averaged for each vendor and found to be all just under X%. The inter-site COVs (and inter-site ANOVA p-values) were X% (p=X) for GE, X% (p=X) for Philips and X% (p=X) for Siemens. The inter-vendor difference was significant (p=X), with the Tukey test showing significant differences between {SITE_X} and {SITE_Y} (p-adjusted Z) [and between …]
~~~

A few specifications for the implementation:
- This feature could be activated with the flag `-output-text`, which would write the text, for each contrast, into a text file (append to the same file). 
- The main would call a function `output_text()` that would take care of the formatting and writing into file
- P-values would need to be rounded (e.g 2 decimals?). Either we display `p<0.01` if smaller than that threshold, or we use scientific notation.

**Comment by valosekj** [comment]
Are you working on this? Otherwise, I could implement it.

**Comment by jcohenadad** [comment]
> Are you working on this? Otherwise, I could implement it.

that would be awesome!

**Comment by jcohenadad** [comment]
p.s. i'm editing the description of the issue to add implementation specifications-- please feel free to add specs and/or comment on them. Thanks!
