### ISSUE TITLE
Register with Google Analytics

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#209]
To monitor activity (useful for grant reports, promotion, quantifying visibility, etc.)

**Comment by alexfoias** [comment]
I can work on this.

**Comment by alexfoias** [comment]
@jcohenadad which google account to you want to use for this ?

**Comment by jcohenadad** [comment]
how about `spinalcordmri [at] gmail.com`?

**Comment by alexfoias** [comment]
Fixed. Here is a proof:

![Screen Shot 2020-09-17 at 4 33 03 PM](https://user-images.githubusercontent.com/12564433/93525099-859b7f80-f903-11ea-8f4d-d1747b5a61f9.png)

**Comment by alexfoias** [comment]
This issue can be closed.

**Comment by alexfoias** [comment]
@jcohenadad Can I close this issue ?

**Comment by jcohenadad** [comment]
@alexfoias where is the link to google analytics where we can see the stats?

**Comment by alexfoias** [comment]
https://analytics.google.com/ you have to login with `spinalcordmri [at] gmail.com` and you'll be able to see it.
