### ISSUE TITLE
Sort metrics in order that matches the spine-generic protocol

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#210]
When fetching results from the statistics outputs, it would be more convenient to have the metrics results listed in the same order as in the spine-generic protocol and manuscript: csa_t1, csa_t2, csa-gm, mtr, mtsat, t1, fa, md, rd.

We could do that by defining a list of metrics, and looping across this list.

**Comment by valosekj** [comment]
Sounds good. We could use some of existing dict, reorder its items to match order with the paper and use its keys as a list of metrics, e.g. 

https://github.com/spine-generic/spine-generic/blob/0496b8f97e6be8ece76bef30b8c80d05f28508ac/spinegeneric/cli/generate_figure.py#L128-L138
