### ISSUE TITLE
Generate the figures dynamically from dashboard

### ISSUE THREAD

**Issue by alexfoias** [spine-generic/spine-generic#239]
The idea is to generate the figures from [results](https://github.com/spine-generic/data-multi-subject/releases/download/r20201001/results.zip) dynamically when RTD builds the documentation.

Using htmls generated in the dashboard https://github.com/spine-generic/spine-generic/issues/222, we'll update the figures.

Implementation in progress on [this branch](https://github.com/spine-generic/spine-generic/tree/af/interactive_fig) which is derivated from https://github.com/spine-generic/spine-generic/pull/237

RTD test page: https://spine-generic.readthedocs.io/en/af-interactive_fig/

**Comment by jcohenadad** [comment]
awesome @alexfoias ! could you please open a PR?
