### ISSUE TITLE
docs/body-size-pipeline.rst is not shown on the documentation website

### ISSUE THREAD

**Issue by renelabounek** [spine-generic/spine-generic#259]
https://spine-generic.readthedocs.io/

No "Body size pipeline" shown.
Do you see what I have missed to edit in the files:
docs/body-size-pipeline.rst
docs/index.rst

**Comment by valosekj** [comment]
Fixed after https://github.com/spine-generic/spine-generic/pull/269 merge.

<img width="303" alt="image" src="https://github.com/spine-generic/spine-generic/assets/39456460/f95a8a79-1249-48e5-be8b-a4e5292678eb">
