### ISSUE TITLE
ReadTheDocs builds failing due to missing `results.zip` asset on recent `data-multi-subject` releases

### ISSUE THREAD

**Issue by mguaypaq** [spine-generic/spine-generic#268]
@valosekj reported on Slack that the documentation seems to no longer be updating:
> Hey! Do you know why https://spine-generic.readthedocs.io/ still shows the old content, although [my PR](https://github.com/spine-generic/spine-generic/pull/267) was merged several days ago?

Looking at [the builds page](https://readthedocs.org/projects/spine-generic/builds/), it looks like the ReadTheDocs builds have been failing since [November 15, 2021](https://readthedocs.org/projects/spine-generic/builds/15274509/), and the last successful build was [October 6, 2021](https://readthedocs.org/projects/spine-generic/builds/14915013/) (almost 2 years ago).

This is maybe also the reason for #259. Maybe also related to #250, although that was before, and wasn't reproducible.

**Comment by mguaypaq** [comment]
Looking at the most recent build output, it seems that the code relies on downloading a `results.zip` asset from the latest release of [spine-generic/data-multi-subject](https://github.com/spine-generic/data-multi-subject):

https://github.com/spine-generic/spine-generic/blob/26c3c3baa6479a3932cf3fb4d80176cea4beaec0/docs/conf.py#L42-L52

However, there are only two releases ([r20201001](https://github.com/spine-generic/data-multi-subject/releases/tag/r20201001) and [r20201130](https://github.com/spine-generic/data-multi-subject/releases/tag/r20201130)) which actually contain this file as an asset. The 3 previous releases contain a similarly-but-differently named file. The following releases don't have anything similar.

So, the release from November 25, 2021, with its missing asset `results.zip`, has caused most of the recent failures. But the error message from the first failure, [November 15, 2021](https://readthedocs.org/projects/spine-generic/builds/15274509/), is different. I'll keep looking.

**Comment by mguaypaq** [comment]
I've opened a PR with a quick fix, but I guess the better long-term solution is to:
1. Re-generate `results.zip` for the most recent release of data-multi-subject, and attach it as an asset.
2. Document the process for doing this.
3. Optionally, automate this process so that we don't forget to do it again in the future.

Separately, the quick fix makes the ReadTheDocs pages build successfully, but there are warning to address, and the whole thing is running on Python 3.7, which is end-of-lifed, and probably ancient versions of various dependencies. It would be nice to clean up and update everything.

**Comment by mguaypaq** [comment]
On the ReadTheDocs configuration page for this project, I'm seeing a deprecation warning with a deadline that's a little less than 1 month away:
![image](https://github.com/spine-generic/spine-generic/assets/928742/6c890348-a12f-4971-bb5e-2bd3321fa63e)

I'll look into doing the migration.

**Comment by joshuacwnewton** [comment]
> I'm seeing a deprecation warning with a deadline that's a little less than 1 month away:

Good catch! I'm seeing this in SCT's [settings dashboard](https://readthedocs.org/dashboard/spinalcordtoolbox/advanced/) as well. I'll open an issue for SCT, too.

**Comment by mguaypaq** [comment]
I'll note here that the current contents of `results.zip` is these files:
```
├── __MACOSX
│   └── spine_generic_multi_20201001
│       ├── ._.DS_Store
│       ├── ._results
│       └── results
│           ├── ._csa-GM_T2s.csv
│           ├── ._csa-SC_T1w.csv
│           ├── ._csa-SC_T2w.csv
│           ├── ._.DS_Store
│           ├── ._DWI_FA.csv
│           ├── ._DWI_MD.csv
│           ├── ._DWI_RD.csv
│           ├── ._fig_dti_md.png
│           ├── ._fig_dti_rd.png
│           ├── ._log_stats.txt
│           ├── ._MTR.csv
│           ├── ._MTsat.csv
│           └── ._T1.csv
└── spine_generic_multi_20201001
    ├── .DS_Store
    └── results
        ├── csa-GM_T2s.csv
        ├── csa-SC_T1w.csv
        ├── csa-SC_T2w.csv
        ├── .DS_Store
        ├── DWI_FA.csv
        ├── DWI_MD.csv
        ├── DWI_RD.csv
        ├── fig_csa_gm.png
        ├── fig_csa_t1.png
        ├── fig_csa_t2.png
        ├── fig_dti_fa.png
        ├── fig_dti_md.png
        ├── fig_dti_rd.png
        ├── fig_mtr.png
        ├── fig_mtsat.png
        ├── fig_t1.png
        ├── fig_t1_t2_agreement_per_vendor.png
        ├── fig_t1_t2_agreement.png
        ├── log_stats.txt
        ├── MTR.csv
        ├── MTsat.csv
        ├── participants.tsv
        └── T1.csv
```

Given the `__MACOSX` and `.DS_Store` files, I suspect that this file was manually generated. I'm also a little bit suspicious of the date-like string `20201001`, which doesn't match the release date `r20201130`.
