### ISSUE TITLE
`process_data.sh` - dorsal columns labels

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#271]
@renelabounek, is `-l 0,1,15,16` in the following commands correct?

https://github.com/spine-generic/spine-generic/blob/f6814fdb2028fe3d1a5d8a7bb60d38b9a447f5db/process_data.sh#L312-L315

Dorsal columns (DC) consist of fasciculus gracilis and fasciculus cuneatus, i.e., `-l 0,1,2,3`; see [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8a49d2949a3bf2affb56501be7cffae077a134e6/documentation/source/overview/concepts/info_label-atlas.txt#L5-L8), alternatively, the combined label `-l 53` can be used; see [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8a49d2949a3bf2affb56501be7cffae077a134e6/documentation/source/overview/concepts/info_label-atlas.txt#L49).

Similarly, lateral corticospinal tract (LCST) uses [`-l 4,5`](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/8a49d2949a3bf2affb56501be7cffae077a134e6/documentation/source/overview/concepts/info_label-atlas.txt#L9-L10) instead of `-l 2,17`:

https://github.com/spine-generic/spine-generic/blob/f6814fdb2028fe3d1a5d8a7bb60d38b9a447f5db/process_data.sh#L308-L311

**Comment by valosekj** [comment]
Also, we can consider using the `-method map` (_maximum a posteriori_ method) instead of the default `-wa` (_weighted average_). The `map` method is recommended for smaller tracts (here DC and LCST).

**Comment by renelabounek** [comment]
We can update it. However, DC and LCST are not small tracts, right? I am finishing grants and almost getting to finishing this analysis.

**Comment by renelabounek** [comment]
@valosekj Hi Jan, just to confirm. With the current atlas labels, LCST is -l 4,5 and DC can be -l 53. Right?

**Comment by valosekj** [comment]
> @valosekj Hi Jan, just to confirm. With the current atlas labels, LCST is -l 4,5 and DC can be -l 53. Right?

Hey René! Correct!

[LCST](https://github.com/spinalcordtoolbox/PAM50/blob/master/atlas/info_label.txt#L9-L10):

```
4, WM left lateral corticospinal tract, PAM50_atlas_04.nii.gz
5, WM right lateral corticospinal tract, PAM50_atlas_05.nii.gz
```

[DC](https://github.com/spinalcordtoolbox/PAM50/blob/master/atlas/info_label.txt#L49):

```
53, dorsal columns, 0:3
```

**Comment by valosekj** [comment]
LCST and DC tracts numbers fixed in https://github.com/spine-generic/spine-generic/pull/276/commits/352eaa35e5ee6d8446cf0dd1736171a348f6576e

**Comment by valosekj** [comment]
> However, DC and LCST are not small tracts, right?

You are right. Agree. We kept the default method (`-wa`) in https://github.com/spine-generic/spine-generic/pull/276.
