### ISSUE TITLE
generate_figure.py input parameters

### ISSUE THREAD

**Issue by valosekj** [spine-generic/spine-generic#63]
The [generate_figure.py](https://github.com/sct-pipeline/spine-generic/blob/master/processing/generate_figure.py) script usage could be more convenient if results directory could be set as input parameter, how is proposed in this TODO:

https://github.com/sct-pipeline/spine-generic/blob/aa697cd96f664c593d7f69670605c43f4bc9fe2f/processing/generate_figure.py#L450

Maybe, also data directory which contains participants.tsv file could be set as input parameter:

https://github.com/sct-pipeline/spine-generic/blob/aa697cd96f664c593d7f69670605c43f4bc9fe2f/processing/generate_figure.py#L214

I can do it, if it looks okay for you @jcohenadad.

**Comment by jcohenadad** [comment]
> The generate_figure.py script usage could be more convenient if results directory could be set as input parameter.

yup, but i would keep default behaviour as it is--  more convenient (i.e. no need to type additional stuff in the CLI)

> Maybe, also data directory which contains participants.tsv file could be set as input parameter:

this is somewhat less needed, thanks to the recent change that copies this file under results/data: https://github.com/sct-pipeline/spine-generic/commit/96a772c6546233d8271dd441b5f78d3f9f8956f4

**Comment by valosekj** [comment]
> > The generate_figure.py script usage could be more convenient if results directory could be set as input parameter.
> 
> yup, but i would keep default behaviour as it is-- more convenient (i.e. no need to type additional stuff in the CLI)
> 

I understand. So, it could be an optional argument for situation when user would like to enforce "another results" directory.
