### ISSUE TITLE
Add manual correction scripts to the repository

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#85]
instead of asking people to copy/paste the content of the scripts [here](https://spine-generic.readthedocs.io/en/latest/documentation.html#segmentation), let's just add those scripts to this repository, and ask users to run them.

**Comment by valosekj** [comment]
We did conclusion to create python script `manual_correction.py` instead of bash script. Python has better yml and args parsers and is easier to debug.
WIP is [here](https://github.com/spine-generic/spine-generic/blob/jv/python_manual_correction_script/processing/manual_correction.py).

**Comment by jcohenadad** [comment]
@valosekj can you open a PR and reference this issue in the PR (standard practice)-- thanks
