### ISSUE TITLE
Mix between date of birth and date of scan

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#86]
example from: https://openneuro.org/datasets/ds002902/versions/1.0.0/file-display/participants.tsv

![image](https://user-images.githubusercontent.com/2482071/85348673-5030f280-b4ca-11ea-8b5e-0df0e604c351.png)

**Comment by jcohenadad** [comment]
@alexfoias do you have any update?

**Comment by alexfoias** [comment]
sorry I missed this issue. I'll fix it this afternoon.

**Comment by alexfoias** [comment]
@jcohenadad I cannot create branch in https://github.com/spine-generic/data-multi-subject. Could you please give me the permissions? thanks

**Comment by jcohenadad** [comment]
@alexfoias can you fork the data-multi-subject repos please? for this repos we will only work with forks (too sensitive)-- thanks
