### ISSUE TITLE
openneuro download is unreliable-- instruct in the doc to not use it

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/spine-generic#97]
when using:
~~~
 openneuro download --snapshot 1.0.4 ds002900 ds002900-download/
~~~

it stops downloading after a few min, without the command stopping. I have to manually stop, and start again. Like 10 times for this dataset.

so, instead of using this command, we should instruct to use aws instead (to be tested!)

**Comment by jcohenadad** [comment]
Update: aws is **also** unreliable. See: https://github.com/OpenNeuroOrg/openneuro/issues/1154#issuecomment-650620936

**Comment by jcohenadad** [comment]
Other issues with openneuro (list below is not exhaustive):
- https://github.com/OpenNeuroOrg/openneuro/issues/1653
- https://github.com/OpenNeuroOrg/openneuro/issues/1463
- https://neurostars.org/t/cannot-find-latest-version-when-updating-datalad-datasets/4679
- https://neurostars.org/t/dysfunctional-search-feature-in-openneuro-website/4983
- https://neurostars.org/t/openneuro-feature-request-link-to-latest-snapshot/4463
- https://neurostars.org/t/unseen-openneuro-datasets-in-datalad/4448
- https://github.com/OpenNeuroOrg/openneuro/issues/1668

**Comment by kousu** [comment]
`openneuro download` also corrupts the download sometimes:

* https://github.com/OpenNeuroOrg/openneuro/issues/1692
* https://github.com/OpenNeuroOrg/openneuro/issues/1693

(I've [fixed this](https://github.com/OpenNeuroOrg/openneuro/pull/1701). Or attempted to anyway. Needs some testing but I'm reasonably confident in it)

**Comment by jcohenadad** [comment]
Data were moved from openneuro to github, so we can now close this issue
